## roles/ansible-role-syslogclient/tasks/main.yml
# vim:ft=yaml.ansible:
---
- name: Include OS-specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Install rsyslog
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ syslogserverPackages }}'
  notify: restart rsyslog

- name: Configure rsyslog
  template:
    src: etc_rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    # -rw-r--r--. root root system_u:object_r:syslog_conf_t:s0
    mode: 0600
    owner: root
    group: root
    seuser: system_u
    serole: object_r
    setype: syslog_conf_t
    backup: yes
  notify: restart rsyslog
...
